# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build TypeScript
RUN npm run build

# Default command to start the MCP server
ENTRYPOINT ["node", "dist/index.js"]
